In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

import sys

'''
Reusing code:
https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/

Explaining result:
https://datascience.stackexchange.com/questions/65839/macro-average-and-weighted-average-meaning-in-classification-report


Test_fearMat_Clean: 4168
    Before edit: 4231 rows × 34 columns
    After edit: 4168 rows × 34 columns
    
    #removed 6 to 7
    total = 3749         (20% = 750; 80% = 2,999)
    

Train_fearMat_Clean: 16680
    Before edit: 16927 rows × 34 columns
    After edit: 16680 rows × 34 columns
    
    #removed 6 to 7
    total = 15045         (20% = 3,009; 80% = 12,036)

'''

import os
#print(os.listdir(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900"))         #print out what's in the file/directory

#train = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\featMatVersion2_10.csv")         #using test


print(os.listdir(r"."))         #print out what's in the file/directory
train = pd.read_csv(r"featMatVersion2_10.csv")

#upload the csv to google colab
#for some reason need to do this each time
#need to find a way to store and acces from drive

#pd.read_csv('/My Drive/Collab Notebooks/featMatVersion2_10.csv')


#train = pd.read_csv(r"Test_dataset.csv")         #using test
#test = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\Train_dataset.csv")

['.config', 'featMatVersion2_10.csv', 'sample_data']


In [ ]:
#print
train.head()

User_ID  Doc_ID  ...  Change of finger orientation  Phone orientation
0       37       4  ...                             0                  1
1       37       4  ...                             0                  1
2       37       4  ...                             0                  1
3       37       4  ...                             0                  1
4       37       4  ...                             0                  1

[5 rows x 34 columns]

In [ ]:
np.any(np.isnan(train))

False

In [ ]:
np.all(np.isfinite(train))

True

In [ ]:
#print out the columns
train.columns

Index(['User_ID', 'Doc_ID', 'Inter-Stroke time', 'Stroke Duration', 'Start X',
       'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
       'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time',
       'Phone_ID', '20 per pairwise velocity', '50 per pairwise velocity',
       '80 per pairwise velocity', '20 per pairwise acc',
       '50 per pairwise acc', '80 per pairwise acc',
       'Median velocity at last 3pts',
       'Largest deviation from end-to-end line', '20 per dev line',
       '50 per dev line', '80 per dev line', 'Average Direction',
       'Length of Trajectory', 'Ratio dist and length of trajectory',
       'Average velocity', 'Median acceleration at first 5 pts',
       'Mid-Stroke pressure', 'Mid-Stroke area covered',
       'Mid-Stroke finger orientation', 'Change of finger orientation',
       'Phone orientation'],
      dtype='object')

In [ ]:
#prints the amount of users in 'User_ID'
train['User_ID'].value_counts()

2     1230
35    1063
23     969
38     786
3      759
15     719
33     712
28     710
17     706
21     702
14     651
8      618
34     613
27     609
7      591
6      562
36     500
18     461
9      453
11     445
29     439
39     436
24     435
25     432
37     424
5      413
1      401
10     387
16     382
22     374
31     370
20     356
12     342
40     312
13     305
32     304
19     293
26     242
4      241
30     225
41     186
Name: User_ID, dtype: int64

In [ ]:
#Choosing the columns for X
#Not using 'User_ID', 'Doc_ID', or 'Phone_ID'
X = train[['Inter-Stroke time', 'Stroke Duration', 'Start X', 'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
        'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time', '20 per pairwise velocity', 
        '50 per pairwise velocity', '80 per pairwise velocity', '20 per pairwise acc', '50 per pairwise acc', 
        '80 per pairwise acc', 'Median velocity at last 3pts', 'Largest deviation from end-to-end line', '20 per dev line',
        '50 per dev line', '80 per dev line', 'Average Direction', 'Length of Trajectory', 
        'Ratio dist and length of trajectory', 'Average velocity', 'Median acceleration at first 5 pts',
        'Mid-Stroke pressure', 'Mid-Stroke area covered', 'Mid-Stroke finger orientation', 'Change of finger orientation',
        'Phone orientation']].values

In [ ]:
#Choosing the lables for y
y = train['User_ID'].values

In [ ]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [ ]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 43   0   0 ...   0   0   1]
 [  0 221   0 ...   2   3   0]
 [  0   1  83 ...   0   1   0]
 ...
 [  0   2   2 ...  42   0   0]
 [  0   1   4 ...   0  26   0]
 [  1   0   0 ...   0   0  26]]
              precision    recall  f1-score   support

           1       0.61      0.65      0.63        66
           2       0.76      0.87      0.81       253
           3       0.54      0.47      0.50       178
           4       0.62      0.70      0.66        43
           5       0.40      0.45      0.42        77
           6       0.60      0.67      0.64       113
           7       0.61      0.51      0.56       119
           8       0.49      0.60      0.54       120
           9       0.72      0.77      0.75        97
          10       0.59      0.57      0.58        82
          11       0.56      0.70      0.62        86
          12       0.74      0.80      0.77        71
          13       0.45      0.37      0.41        65
          14       0.61      0.81      0.70       1

In [ ]:
#prints the entire confusion matrix
#however, it doesnn't fit the entire row and loops around
np.set_printoptions(threshold=sys.maxsize)
resultCM = (confusion_matrix(y_test, y_pred))
print(resultCM)

[[ 43   0   0   2   0   0   6   1   0   0   0   0   0   0   0   0   0   0
    0   1   0   2   2   0   0   1   0   4   0   0   0   0   0   2   0   1
    0   0   0   0   1]
 [  0 221   0   0   0   0   0   1   4   1   0   0   1   0   5   0   0   0
    0   0   0   0   6   2   1   0   0   2   1   0   0   0   0   0   0   1
    1   1   2   3   0]
 [  0   1  83   1   4   3   0   6   0   2   6   2   1   1   0   2  23   3
    4   0   5   0   0   0   1   0   9   0   0   0   0   2   1   0  14   0
    3   0   0   1   0]
 [  3   1   0  30   0   0   1   0   0   0   0   0   0   1   0   0   0   0
    0   0   0   1   1   0   0   0   0   1   0   1   0   0   0   1   0   0
    0   0   1   0   1]
 [  0   2   5   0  35   2   0   7   6   1   0   4   0   0   0   2   0   0
    4   0   0   0   1   0   0   0   0   0   0   0   0   1   1   0   1   1
    0   0   0   4   0]
 [  0   0   4   0   2  76   0   5   0   1   2   1   2   1   0   6   3   0
    0   0   2   0   0   1   0   0   2   0   0   0   0   0   0   0   3  

In [ ]:
resultCR = (classification_report(y_test, y_pred))
print(resultCR)

              precision    recall  f1-score   support

           1       0.61      0.65      0.63        66
           2       0.76      0.87      0.81       253
           3       0.54      0.47      0.50       178
           4       0.62      0.70      0.66        43
           5       0.40      0.45      0.42        77
           6       0.60      0.67      0.64       113
           7       0.61      0.51      0.56       119
           8       0.49      0.60      0.54       120
           9       0.72      0.77      0.75        97
          10       0.59      0.57      0.58        82
          11       0.56      0.70      0.62        86
          12       0.74      0.80      0.77        71
          13       0.45      0.37      0.41        65
          14       0.61      0.81      0.70       134
          15       0.61      0.71      0.65       130
          16       0.38      0.48      0.42        71
          17       0.63      0.62      0.62       151
          18       0.77    

In [ ]:
'''
'macro':
 Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

'weighted':
 Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label).
 This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.
'''

"\n'macro':\n Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.\n\n'weighted':\n Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label).\n This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.\n"

In [ ]:
#Code had to be modify a little to be compatable with my current Tensorflow
#Convert Tensorflow2 to Tensorflow1 to run some part of the code
#There was still an issue with one part of the code but everything else seems fine

'''
https://www.kaggle.com/nihalbey/knn-with-tensorflow/notebook
'''


# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow.compat.v1 as tf
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

In [ ]:
import tensorflow.compat.v1 as tf