In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

import sys

'''
Reusing code:
https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/

Explaining result:
https://datascience.stackexchange.com/questions/65839/macro-average-and-weighted-average-meaning-in-classification-report


Test_fearMat_Clean: 4168
    Before edit: 4231 rows × 34 columns
    After edit: 4168 rows × 34 columns
    
    #removed 6 to 7
    total = 3749         (20% = 750; 80% = 2,999)
    

Train_fearMat_Clean: 16680
    Before edit: 16927 rows × 34 columns
    After edit: 16680 rows × 34 columns
    
    #removed 6 to 7
    total = 15045         (20% = 3,009; 80% = 12,036)

'''

import os
#print(os.listdir(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900"))         #print out what's in the file/directory

#train = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\featMatVersion2_10.csv")         #using test


print(os.listdir(r"."))         #print out what's in the file/directory
train = pd.read_csv(r"featMatVersion2_10.csv")


#train = pd.read_csv(r"Test_dataset.csv")         #using test
#test = pd.read_csv(r"C:\Users\eddie\OneDrive\Desktop\CISC 4900\Train_dataset.csv")

['Project Code 2 Part 1.ipynb', 'Untitled10.ipynb', 'Untitled7.ipynb', 'EditingDataset_V3.java', 'Untitled12.ipynb', 'Untitled5.ipynb', 'Untitled1.ipynb', 'Untitled16.ipynb', '.DS_Store', 'CodeVersion3b.py', 'previous', 'Untitled3.ipynb', 'JNCode1.py', 'Untitled14.ipynb', 'Untitled.ipynb', 'ClassificationReport_2R.txt', 'Untitled4.ipynb', 'Untitled13.ipynb', 'Project Code 2 Part 2.ipynb', 'Untitled6.ipynb', 'DataSet_V4.csv', 'Untitled11.ipynb', 'Old Code', 'ConfusionMatrix_1R.csv', 'Untitled15.ipynb', 'Untitled2.ipynb', '__pycache__', 'Untitled17.ipynb', 'Script', 'README.md', 'Untitled19.ipynb', 'featMatVersion2_10.csv', 'CodeVersion2', 'Untitled20.ipynb', 'ConfusionMatrix_2R.csv', 'Untitled8.ipynb', 'ClassificationReport_1R.txt', 'Sample Code', '.ipynb_checkpoints', 'Untitled18.ipynb', '.git', 'CodeVersion3.py', 'Data', 'Untitled9.ipynb', 'Untitled21.ipynb']


In [2]:
#print
train.head()

User_ID  Doc_ID  Inter-Stroke time  Stroke Duration  Start X  Start Y  \
0       37       4              0.341            0.256   27.416  -27.113   
1       37       4              0.913            0.086   21.771  -30.037   
2       37       4              0.733            0.111   10.886  -34.169   
3       37       4              0.448            0.094   19.151  -34.572   
4       37       4              0.519            0.056   27.718  -32.758   

    Stop X  Stop Y  Direct end-to-end Distance  Mean resulant length  ...  \
0  12.3980 -32.960                     16.1160               0.35736  ...   
1   9.8778 -33.867                     12.4950               0.26504  ...   
2  26.9120 -34.673                     16.0340               0.99118  ...   
3  12.7000 -36.790                      6.8213               0.59647  ...   
4  14.6150 -37.294                     13.8660               0.67819  ...   

   Average Direction  Length of Trajectory  \
0          -2.581200               16.1320   
1          -2.199400               12.5960   
2           0.086288               16.2030   
3          -2.723100                6.9674   
4          -2.717000               13.8710   

   Ratio dist and length of trajectory  Average velocity  \
0                              0.99898            63.018   
1                              0.99197           146.470   
2                              0.98959           145.970   
3                              0.97902            74.122   
4                              0.99965           247.690   

   Median acceleration at first 5 pts  Mid-Stroke pressure  \
0                             -432.24                 0.32   
1                             5117.70                 0.60   
2                            -3563.50                 0.48   
3                            -4604.10                 0.40   
4                           -21377.00                 0.44   

   Mid-Stroke area covered  Mid-Stroke finger orientation  \
0                 0.044444                            0.0   
1                 0.088889                            0.0   
2                 0.044444                            0.0   
3                 0.044444                            0.0   
4                 0.044444                            0.0   

   Change of finger orientation  Phone orientation  
0                             0                  1  
1                             0                  1  
2                             0                  1  
3                             0                  1  
4                             0                  1  

[5 rows x 34 columns]

In [3]:
np.any(np.isnan(train))

False

In [4]:
np.all(np.isfinite(train))

True

In [5]:
#print out the columns
train.columns

Index(['User_ID', 'Doc_ID', 'Inter-Stroke time', 'Stroke Duration', 'Start X',
       'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
       'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time',
       'Phone_ID', '20 per pairwise velocity', '50 per pairwise velocity',
       '80 per pairwise velocity', '20 per pairwise acc',
       '50 per pairwise acc', '80 per pairwise acc',
       'Median velocity at last 3pts',
       'Largest deviation from end-to-end line', '20 per dev line',
       '50 per dev line', '80 per dev line', 'Average Direction',
       'Length of Trajectory', 'Ratio dist and length of trajectory',
       'Average velocity', 'Median acceleration at first 5 pts',
       'Mid-Stroke pressure', 'Mid-Stroke area covered',
       'Mid-Stroke finger orientation', 'Change of finger orientation',
       'Phone orientation'],
      dtype='object')

In [6]:
#prints the amount of users in 'User_ID'
train['User_ID'].value_counts()

2     1230
35    1063
23     969
38     786
3      759
15     719
33     712
28     710
17     706
21     702
14     651
8      618
34     613
27     609
7      591
6      562
36     500
18     461
9      453
11     445
29     439
39     436
24     435
25     432
37     424
5      413
1      401
10     387
16     382
22     374
31     370
20     356
12     342
40     312
13     305
32     304
19     293
26     242
4      241
30     225
41     186
Name: User_ID, dtype: int64

In [7]:
#Choosing the columns for X
#Not using 'User_ID', 'Doc_ID', or 'Phone_ID'
X = train[['Inter-Stroke time', 'Stroke Duration', 'Start X', 'Start Y', 'Stop X', 'Stop Y', 'Direct end-to-end Distance',
        'Mean resulant length', 'WSAD Flag', 'Direction of end-to-end Time', '20 per pairwise velocity', 
        '50 per pairwise velocity', '80 per pairwise velocity', '20 per pairwise acc', '50 per pairwise acc', 
        '80 per pairwise acc', 'Median velocity at last 3pts', 'Largest deviation from end-to-end line', '20 per dev line',
        '50 per dev line', '80 per dev line', 'Average Direction', 'Length of Trajectory', 
        'Ratio dist and length of trajectory', 'Average velocity', 'Median acceleration at first 5 pts',
        'Mid-Stroke pressure', 'Mid-Stroke area covered', 'Mid-Stroke finger orientation', 'Change of finger orientation',
        'Phone orientation']].values

In [8]:
#Choosing the lables for y
y = train['User_ID'].values

In [9]:
#Train and test split
#80% train, 20% test
#splitting the data into test and train dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [10]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
#Training and Prediction
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)         #value for k
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [12]:
#Make prediction on the test data
y_pred = classifier.predict(X_test)

In [13]:
#Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 59   0   0 ...   1   0   1]
 [  0 224   0 ...   2   0   0]
 [  0   2  67 ...   1   1   0]
 ...
 [  0   4   4 ...  37   0   0]
 [  0   1   1 ...   0  37   0]
 [  1   0   0 ...   0   0  24]]
              precision    recall  f1-score   support

           1       0.70      0.64      0.67        92
           2       0.75      0.90      0.82       250
           3       0.50      0.46      0.48       147
           4       0.68      0.75      0.72        52
           5       0.46      0.63      0.53        83
           6       0.67      0.71      0.69       126
           7       0.67      0.63      0.65       131
           8       0.57      0.75      0.64       126
           9       0.74      0.90      0.82        83
          10       0.65      0.56      0.60        90
          11       0.56      0.74      0.64        84
          12       0.81      0.80      0.80        74
          13       0.52      0.35      0.42        68
          14       0.65      0.89      0.75       1

In [14]:
#prints the entire confusion matrix
#however, it doesnn't fit the entire row and loops around
np.set_printoptions(threshold=sys.maxsize)
resultCM = (confusion_matrix(y_test, y_pred))
print(resultCM)

[[ 59   0   0   6   0   0   4   0   0   0   0   0   0   0   3   0   0   0
    0   0   0   6   1   0   0   0   0   4   0   2   0   0   0   1   0   1
    1   2   1   0   1]
 [  0 224   0   1   0   0   2   0   0   0   0   0   0   1   1   0   0   0
    0   0   0   2   3   1   3   0   0   0   1   0   0   0   2   0   1   2
    0   4   2   0   0]
 [  0   2  67   0   5   3   1   4   1   3   4   0   0   0   0   4  21   6
    0   0   3   0   0   0   0   0   7   0   0   0   0   1   0   0  12   0
    1   0   1   1   0]
 [  3   1   0  39   1   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   1   0   0   1   0   2   0   3   0   0   0   1   0   0
    0   0   0   0   0]
 [  0   1   5   0  52   2   0   5   4   1   0   0   0   0   0   0   1   0
    2   0   0   0   1   0   0   0   3   0   0   1   1   0   0   1   0   0
    1   0   0   2   0]
 [  0   0   5   0   1  90   1   6   0   1   0   0   3   1   0   5   2   1
    1   0   2   0   0   0   0   0   2   1   0   0   0   0   0   0   2  

In [15]:
resultCR = (classification_report(y_test, y_pred))
print(resultCR)

              precision    recall  f1-score   support

           1       0.70      0.64      0.67        92
           2       0.75      0.90      0.82       250
           3       0.50      0.46      0.48       147
           4       0.68      0.75      0.72        52
           5       0.46      0.63      0.53        83
           6       0.67      0.71      0.69       126
           7       0.67      0.63      0.65       131
           8       0.57      0.75      0.64       126
           9       0.74      0.90      0.82        83
          10       0.65      0.56      0.60        90
          11       0.56      0.74      0.64        84
          12       0.81      0.80      0.80        74
          13       0.52      0.35      0.42        68
          14       0.65      0.89      0.75       134
          15       0.74      0.79      0.77       130
          16       0.35      0.40      0.37        73
          17       0.66      0.68      0.67       139
          18       0.78    

In [16]:
'''
'macro':
 Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

'weighted':
 Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label).
 This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.
'''

"\n'macro':\n Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.\n\n'weighted':\n Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label).\n This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.\n"